{
  "language": "node_js",
  "node_js": "8",
  "script": [
    "npm run lint",
    "npm run build",
    "npm run test"
  ],
  "before_install": [
    "sudo apt update",
    "sudo apt install jpegoptim advancecomp gifsicle pngquant imagemagick"
  ],
  "install": [
    "npm ci"
  ],
}