version: "2"
services:
    redis:
        image: "redis"
    mwoffliner:
        stdin_open: true
        tty: true
        build:
            dockerfile: Dockerfile
            context: ./
        links:
            - redis
